<Type Name="Catch&lt;TException&gt;" FullName="System.Activities.Statements.Catch&lt;TException&gt;">
  <TypeSignature Language="C#" Value="public sealed class Catch&lt;TException&gt; : System.Activities.Statements.Catch where TException : Exception" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi sealed beforefieldinit Catch`1&lt;(class System.Exception) TException&gt; extends System.Activities.Statements.Catch" />
  <TypeSignature Language="DocId" Value="T:System.Activities.Statements.Catch`1" />
  <AssemblyInfo>
    <AssemblyName>System.Activities</AssemblyName>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <TypeParameters>
    <TypeParameter Name="TException">
      <Constraints>
        <BaseTypeName>System.Exception</BaseTypeName>
      </Constraints>
    </TypeParameter>
  </TypeParameters>
  <Base>
    <BaseTypeName>System.Activities.Statements.Catch</BaseTypeName>
  </Base>
  <Interfaces />
  <Attributes>
    <Attribute>
      <AttributeName>System.Windows.Markup.ContentProperty("Action")</AttributeName>
    </Attribute>
  </Attributes>
  <Docs>
    <typeparam name="TException">
      <see cref="T:System.Activities.Statements.Catch`1" /> ブロックが処理している例外の種類。</typeparam>
    <summary>
      <see cref="T:System.Activities.Statements.TryCatchFinally" /> アクティビティの対応する Try ブロックに例外が発生した後に実行される、アクションを含みます。</summary>
    <remarks>
      <format type="text/markdown"><![CDATA[  
  
## 解説  
 デザイナーに配置される<xref:System.Activities.Statements.Catch>デザイナーでアクティビティを並べ替えることができません。  コレクションを並べ替えるには<xref:System.Activities.Statements.Catch>アクティビティ、削除が正しい順序で追加し直すかワークフローの xaml \(コード\) ビューを使用します。  
  
   
  
## 例  
 <xref:System.Activities.Statements.Catch%601> アクティビティを作成するコード サンプルを次に示します。 この例は、[フローチャート アクティビティを使用して TryCatch のエラーの処理](http://msdn.microsoft.com/ja-jp/50922964-bfe0-4ba8-9422-0e7220d514fd)サンプルです。  
  
 [!code-csharp[wfs\_FlowChartWithFaultHandling\#1](~/samples/snippets/csharp/VS_Snippets_CFX/wfs_flowchartwithfaulthandling/cs/program.cs#1)]  
  
 ]]></format>
    </remarks>
  </Docs>
  <Members>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public Catch ();" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor() cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Activities.Statements.Catch`1.#ctor" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Activities</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters />
      <Docs>
        <summary>
          <see cref="T:System.Activities.Statements.Catch`1" /> クラスの新しいインスタンスを作成します。</summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## 解説  
   
  
## 例  
 次のコード サンプルでは作成、<xref:System.Activities.Statements.Catch%601>アクティビティ。 この例は、[フローチャート アクティビティを使用して TryCatch のエラーの処理](http://msdn.microsoft.com/ja-jp/50922964-bfe0-4ba8-9422-0e7220d514fd)サンプルです。  
  
 [!code-csharp[wfs\_FlowChartWithFaultHandling\#1](~/samples/snippets/csharp/VS_Snippets_CFX/wfs_flowchartwithfaulthandling/cs/program.cs#1)]  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName="Action">
      <MemberSignature Language="C#" Value="public System.Activities.ActivityAction&lt;TException&gt; Action { get; set; }" />
      <MemberSignature Language="ILAsm" Value=".property instance class System.Activities.ActivityAction`1&lt;!TException&gt; Action" />
      <MemberSignature Language="DocId" Value="P:System.Activities.Statements.Catch`1.Action" />
      <MemberType>Property</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Activities</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Attributes>
        <Attribute>
          <AttributeName>System.ComponentModel.DefaultValue(null)</AttributeName>
        </Attribute>
      </Attributes>
      <ReturnValue>
        <ReturnType>System.Activities.ActivityAction&lt;TException&gt;</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>キャッチされている例外のハンドラー。</summary>
        <value>アクティビティ操作。</value>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## 解説  
 例外ハンドラーは、<xref:System.WorkflowModel.ActivityAction> オブジェクトで表されます。  
  
   
  
## 例  
 <xref:System.Activities.Statements.Catch%601> アクティビティの Action プロパティを割り当てるコード サンプルを次に示します。 この例は、[フローチャート アクティビティを使用して TryCatch でエラーの処理](http://msdn.microsoft.com/ja-jp/50922964-bfe0-4ba8-9422-0e7220d514fd)サンプルです。  
  
 [!code-csharp[wfs\_FlowChartWithFaultHandling\#1](~/samples/snippets/csharp/VS_Snippets_CFX/wfs_flowchartwithfaulthandling/cs/program.cs#1)]  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName="ExceptionType">
      <MemberSignature Language="C#" Value="public override Type ExceptionType { get; }" />
      <MemberSignature Language="ILAsm" Value=".property instance class System.Type ExceptionType" />
      <MemberSignature Language="DocId" Value="P:System.Activities.Statements.Catch`1.ExceptionType" />
      <MemberType>Property</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Activities</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.Type</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>
          <see cref="T:System.Activities.Statements.Catch" /> ブロックが処理している例外の種類。</summary>
        <value>例外の種類。</value>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## 解説  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
  </Members>
</Type>