<Type Name="ErrorResponseCategory" FullName="System.DirectoryServices.Protocols.ErrorResponseCategory">
  <TypeSignature Language="C#" Value="public enum ErrorResponseCategory" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi sealed ErrorResponseCategory extends System.Enum" />
  <TypeSignature Language="DocId" Value="T:System.DirectoryServices.Protocols.ErrorResponseCategory" />
  <AssemblyInfo>
    <AssemblyName>System.DirectoryServices.Protocols</AssemblyName>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>System.Enum</BaseTypeName>
  </Base>
  <Docs>
    <summary>
      <see cref="T:System.DirectoryServices.Protocols.ErrorResponseCategory" /> 列挙には可能な DSML エラー応答が含まれています。</summary>
    <remarks>
      <format type="text/markdown"><![CDATA[  
  
## 解説  
 ]]></format>
    </remarks>
  </Docs>
  <Members>
    <Member MemberName="AuthenticationFailed">
      <MemberSignature Language="C#" Value="AuthenticationFailed" />
      <MemberSignature Language="ILAsm" Value=".field public static literal valuetype System.DirectoryServices.Protocols.ErrorResponseCategory AuthenticationFailed = int32(5)" />
      <MemberSignature Language="DocId" Value="F:System.DirectoryServices.Protocols.ErrorResponseCategory.AuthenticationFailed" />
      <MemberType>Field</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.DirectoryServices.Protocols</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.DirectoryServices.Protocols.ErrorResponseCategory</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>認証に失敗しました。 値は 5 に等しいです。</summary>
      </Docs>
    </Member>
    <Member MemberName="ConnectionClosed">
      <MemberSignature Language="C#" Value="ConnectionClosed" />
      <MemberSignature Language="ILAsm" Value=".field public static literal valuetype System.DirectoryServices.Protocols.ErrorResponseCategory ConnectionClosed = int32(2)" />
      <MemberSignature Language="DocId" Value="F:System.DirectoryServices.Protocols.ErrorResponseCategory.ConnectionClosed" />
      <MemberType>Field</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.DirectoryServices.Protocols</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.DirectoryServices.Protocols.ErrorResponseCategory</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>DSML プロバイダーは、サーバーに接続されているが、サーバーが要求に応答することがなく、接続を閉じました。 値は 2 です。</summary>
      </Docs>
    </Member>
    <Member MemberName="CouldNotConnect">
      <MemberSignature Language="C#" Value="CouldNotConnect" />
      <MemberSignature Language="ILAsm" Value=".field public static literal valuetype System.DirectoryServices.Protocols.ErrorResponseCategory CouldNotConnect = int32(1)" />
      <MemberSignature Language="DocId" Value="F:System.DirectoryServices.Protocols.ErrorResponseCategory.CouldNotConnect" />
      <MemberType>Field</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.DirectoryServices.Protocols</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.DirectoryServices.Protocols.ErrorResponseCategory</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>DSML プロバイダーは、サーバーに接続できませんでした。 値は 1 です。</summary>
      </Docs>
    </Member>
    <Member MemberName="GatewayInternalError">
      <MemberSignature Language="C#" Value="GatewayInternalError" />
      <MemberSignature Language="ILAsm" Value=".field public static literal valuetype System.DirectoryServices.Protocols.ErrorResponseCategory GatewayInternalError = int32(4)" />
      <MemberSignature Language="DocId" Value="F:System.DirectoryServices.Protocols.ErrorResponseCategory.GatewayInternalError" />
      <MemberType>Field</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.DirectoryServices.Protocols</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.DirectoryServices.Protocols.ErrorResponseCategory</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>ゲートウェイの内部エラーがあります。 値は 4 です。</summary>
      </Docs>
    </Member>
    <Member MemberName="MalformedRequest">
      <MemberSignature Language="C#" Value="MalformedRequest" />
      <MemberSignature Language="ILAsm" Value=".field public static literal valuetype System.DirectoryServices.Protocols.ErrorResponseCategory MalformedRequest = int32(3)" />
      <MemberSignature Language="DocId" Value="F:System.DirectoryServices.Protocols.ErrorResponseCategory.MalformedRequest" />
      <MemberType>Field</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.DirectoryServices.Protocols</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.DirectoryServices.Protocols.ErrorResponseCategory</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>クライアントは、各要求の要求 ID を指定できませんでした。 値は 3 です。</summary>
      </Docs>
    </Member>
    <Member MemberName="NotAttempted">
      <MemberSignature Language="C#" Value="NotAttempted" />
      <MemberSignature Language="ILAsm" Value=".field public static literal valuetype System.DirectoryServices.Protocols.ErrorResponseCategory NotAttempted = int32(0)" />
      <MemberSignature Language="DocId" Value="F:System.DirectoryServices.Protocols.ErrorResponseCategory.NotAttempted" />
      <MemberType>Field</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.DirectoryServices.Protocols</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.DirectoryServices.Protocols.ErrorResponseCategory</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>DSML プロバイダーは、要求の要素を実行する試みませんでした。 値は 0 になります。</summary>
      </Docs>
    </Member>
    <Member MemberName="Other">
      <MemberSignature Language="C#" Value="Other" />
      <MemberSignature Language="ILAsm" Value=".field public static literal valuetype System.DirectoryServices.Protocols.ErrorResponseCategory Other = int32(7)" />
      <MemberSignature Language="DocId" Value="F:System.DirectoryServices.Protocols.ErrorResponseCategory.Other" />
      <MemberType>Field</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.DirectoryServices.Protocols</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.DirectoryServices.Protocols.ErrorResponseCategory</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>不明なエラーが発生しました。 値は 7 です。</summary>
      </Docs>
    </Member>
    <Member MemberName="UnresolvableUri">
      <MemberSignature Language="C#" Value="UnresolvableUri" />
      <MemberSignature Language="ILAsm" Value=".field public static literal valuetype System.DirectoryServices.Protocols.ErrorResponseCategory UnresolvableUri = int32(6)" />
      <MemberSignature Language="DocId" Value="F:System.DirectoryServices.Protocols.ErrorResponseCategory.UnresolvableUri" />
      <MemberType>Field</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.DirectoryServices.Protocols</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.DirectoryServices.Protocols.ErrorResponseCategory</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>クライアント プロバイダーは、サーバーに転送されることができる値への URI を解決するのにはできません。 値は 6 です。</summary>
      </Docs>
    </Member>
  </Members>
</Type>